version: 1.0.{build}
os: Visual Studio 2017
skip_tags: true
configuration: Debug
build_script:
- ps: dotnet restore ./Trappist/Trappist.sln
environment:  
  COVERALLS_REPO_TOKEN:
  secure: +U8RojpUoVh2Hn/hVkZ+MBV9HyZVPPiATA4WxOYQx3tIkVHQP8QLfaFmLCsCDTvJ
build:
  project: .\Trappist\Trappist.sln
  verbosity: minimal
test_script:
- ps: >-
   cd .\Trappist\src\Promact.Trappist.Test; Start-FileDownload 'https://ci.appveyor.com/api/buildjobs/xj78v6dac42uob8q/artifacts/main%2Fbin%2Fzip%2Fopencover.4.6.589.zip'; 7z.exe x main%2Fbin%2Fzip%2Fopencover.4.6.589.zip
- ps: >-
   .\OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test " -filter:"+[Promact.Trappist.Repository*]*" -hideskipped:File -output:opencover.xml -oldStyle
- ps: >-
   if(![string]::IsNullOrEmpty($env:COVERALLS_REPO_TOKEN)){

   $coveralls = (Resolve-Path "C:\Users\appveyor\.nuget\packages\coveralls.net\0.8.0-unstable0013\tools\csmacnz.coveralls.exe").ToString()
   
   & $coveralls --opencover -i opencover.xml --repoToken $env:COVERALLS_REPO_TOKEN
   }
     

